Repository FSA-Capstone-Midas/Midas, pull requests merged in 2018-05, with the labels that each got.

#5 bug/enhancement: fix errors due to the button and refractor the navbar to its own component
  client/components/AboutUs.js
  client/components/DesktopContainer.js
  client/components/HomePage.js
  client/components/HomepageHeading.js
  client/components/HowItWorks.js
  client/components/MobileContainer.js
  client/components/SignUp.js
  client/components/SignUp1.js
  client/components/index.js
  client/components/navbar.js
  client/routes.js
  public/pictures/feature_link_headline.gif
  public/pictures/matthew.png
  public/style.css
Labels: bug, enhancement

#9 add: front end features
  client/components/HomePage.js
  client/components/HowItWorks.js
  public/fonts/jaapokkienchance-regular.eot
  public/fonts/jaapokkienchance-regular.svg
  public/fonts/jaapokkienchance-regular.ttf
  public/fonts/jaapokkienchance-regular.woff
  public/pictures/BAC.jpg
  public/pictures/CS.png
  public/pictures/Chase.png
  public/pictures/Citibank.jpg
  public/pictures/TD.jpg
  public/pictures/Wells_Fargo_Bank.png
  public/pictures/backgroundNYC.png
  public/pictures/feature_link_solution.gif
  public/pictures/feature_track_headline.gif
  public/pictures/icon-bank.png
  public/pictures/moneypig.gif
  public/pictures/moneypig.png
  public/pictures/veronika.jpg
  public/pictures/wallet.gif
  public/style.css
Labels: enhancement

#14 Add animation when loading a component
  client/components/Loading.js
  client/components/loading.css
  client/components/user-home.js
  client/store/user.js
  public/index.html
  public/loading.css
  public/style.css
Labels: enhancement

#16 Merge with Plaid but now need to fix some problem to fetch plaid info
  client/components/HomePage.js
  client/components/Transactions.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  client/store/plaid.js
  server/api/index.js
  server/index.js
Labels: bug

#19 Fixed redux store , api call for plaid
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/Plaid.js
  client/components/Transactions.js
  client/routes.js
  client/store/plaid.js
  client/store/user.js
  package-lock.json
  server/db/models/user.js
  server/plaid_api/index.js
  server/plaid_api/plaid.js
Labels: bug

#21 fix a redux store error
  client/store/plaid.js
Labels: bug

#22 Add user account on home page, fix error from data map
  client/components/AccountTable.js
  client/components/DataMap.js
  client/components/Transactions.js
  client/components/index.js
  client/components/user-home.js
  public/index.html
  server/index.js
Labels: bug, enhancement

#23 Add: add transaction page for user
  client/components/Transactions.js
  package-lock.json
  package.json
  public/index.html
Labels: enhancement

#26 refactor the redux store state for plaid api
  client/components/AccountTable.js
  client/components/Transactions.js
  client/components/user-home.js
  client/store/accounts.js
  client/store/index.js
  client/store/plaid.js
  client/store/transactions.js
  client/store/user.js
  server/api/plaid.js
Labels: bug

#27 Add: separate the transaction components
  client/components/Transactions.js
  client/components/TransactionsBar.js
  client/components/TransactionsPie.js
  package-lock.json
  package.json
Labels: enhancement

#31 Fix: update the spending graph for user transactions
  client/components/BarIncome.js
  client/components/BarNetIncome.js
  client/components/BarSpending.js
  client/components/HomePage.js
  client/components/PieIncome.js
  client/components/PieSpending.js
  client/components/SideBar.js
  client/components/Table.js
  client/components/Transactions.js
  client/components/TransactionsBar.js
  client/components/utils.js
  package.json
  public/style.css
Labels: bug

#32 added USA map on Trends page
  client/components/DataMapApartmentYYRentChange.js
  client/components/DataMapApartments.js
  client/components/DataMapApartments2Br.js
  client/components/DataMapApartmentsMMRentChange.js
  client/components/DataMapHousing.js
  client/components/UserTrend.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  client/store/index.js
  client/store/state.js
  package-lock.json
  public/style.css
  script/seed.js
  server/api/state.js
  server/db/models/state.js
  server/db/models/user.js
Labels: enhancement

#34 Newbudget
  client/components/Budget.js
  client/components/BudgetInput.js
  client/components/BudgetModal.js
  client/components/HomePage.js
  client/components/HorizontalBarChart.js
  client/components/index.js
  client/store/budget.js
  client/store/index.js
  public/style.css
  server/api/users.js
  server/db/models/user.js
Labels: enhancement

#40 Update the simulation for retirement table and results
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/Retirement.js
  client/components/RetirementResult.js
  client/components/RetirementTable.js
  client/components/Step1.js
  client/components/Step2.js
  client/components/Step3Confirmation.js
  client/components/Transactions.js
  client/components/ZU - Step4Success.js
  client/components/ZU-Step3.js
  client/components/index.js
  client/components/utils.js
  client/routes.js
  client/store/form.js
  client/store/index.js
  package-lock.json
  package.json
  public/index.html
  public/pictures/jenny.jpg
  public/pictures/justen.jpg
  public/style.css
  server/api/index.js
  server/api/retirement.js
  server/db/models/index.js
  server/db/models/retirement.js
Labels: bug

#46 Update the house and retirement goal page
  client/components/Goals.js
  client/components/GoalsComponent.js
  client/components/GoalsMenu.js
  client/components/GoalsRetirement.js
  client/components/House.js
  client/components/HouseGoal.js
  client/components/HouseSaveGoal.js
  client/components/Retirement.js
  client/components/RetirementResult.js
  client/components/RetirementTable.js
  client/components/Step1.js
  client/components/Step2.js
  client/components/Step3Confirmation.js
  client/components/utils.js
  client/routes.js
  client/store/houseForm.js
  client/store/retirement.js
  server/api/house.js
  server/api/index.js
  server/api/retirement.js
  server/db/models/house.js
  server/db/models/index.js
Labels: bug, enhancement

#47 Fix various bugs for code review
  client/components/AboutUs.js
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/Budget.js
  client/components/Footer.js
  client/components/Goals.js
  client/components/GoalsComponent.js
  client/components/GoalsMenu.js
  client/components/Plaid.js
  client/components/Profile.js
  client/components/SaveForEmergency.js
  client/components/SaveForEmergencyConfirmPage.js
  client/components/SaveForEmergencyMainPage.js
  client/components/Step3Confirmation.js
  client/components/Transactions.js
  client/components/UserCredit.js
  client/components/UserTrend.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  client/store/emergencyGoal.js
  client/store/index.js
  client/store/plaid.js
  client/store/retirement.js
  client/store/user.js
  script/seed.js
  semantic/tasks/version.js
  server/api/emergencyGoal.js
  server/api/house.js
  server/api/index.js
  server/auth/index.js
  server/db/models/emergencyGoal.js
  server/db/models/index.js
  server/index.js
Labels: bug, enhancement

#52 User home dashboard and added josh alert bill in home page
  client/components/AccountTable.js
  client/components/BillAlert.js
  client/components/BillForm.js
  client/components/Budget.js
  client/components/Transactions/BarIncome.js
  client/components/Transactions/Transactions.js
  client/components/user-home.js
Labels: enhancement

#60 Update CSS for goals page
  client/components/Budget/Budget.js
  client/components/Budget/BudgetHorizontalBarChart.js
  client/components/Budget/BudgetModal.js
  client/components/Budget/BudgetProgress.js
  client/components/Goals.js
  client/components/Goals/Goals.js
  client/components/Goals/GoalsComponent.js
  client/components/Goals/GoalsMenu.js
  client/components/Goals/GoalsOptions.js
  client/components/Goals/House.js
  client/components/Goals/Retirement.js
  client/components/Goals/RetirementResult.js
  client/components/Goals/RetirementTable.js
  client/components/Goals/SaveForEmergency.js
  client/components/Goals/SaveForEmergencyConfirmPage.js
  client/components/Goals/SaveForEmergencyMainPage.js
  client/components/Goals/Step1.js
  client/components/Goals/Step2.js
  client/components/Goals/Step3Confirmation.js
  client/components/GoalsComponent.js
  client/components/GoalsMenu.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  client/store/emergencyGoal.js
  client/store/houseForm.js
  client/store/retirement.js
  public/pictures/elliot.jpg
  public/style.css
  server/api/emergencyGoal.js
  server/api/house.js
  server/api/retirement.js
Labels: enhancement

#62 Fix various css issues
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/AfterLogin/AfterLoginMobileContainer.js
  client/components/BeforeLogin/DesktopContainer.js
  client/components/BeforeLoginPages/AboutUs.js
  client/components/BeforeLoginPages/HowItWorks.js
  client/components/BeforeLoginPages/Login.js
  client/components/BeforeLoginPages/SignUp.js
  client/components/BillForm.js
  client/components/Budget/Budget.js
  client/components/Budget/BudgetProgress.js
  client/components/Goals/Goals.js
  client/components/Goals/House.js
  client/components/Profile.js
  client/components/Transactions/Transactions.js
  client/components/Trends/UserTrend.js
  client/components/UserCredit.js
  package-lock.json
  public/style.css
Labels: bug, enhancement

#63 add a logo
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/Goals/GoalsOptions.js
  client/components/user-home.js
  public/favicon.ico
  public/favicon1.ico
  public/pictures/emergency.png
  public/pictures/house.png
  public/pictures/midas_nav_logo.png
  public/pictures/retirement.png
  public/style.css
Labels: enhancement

#64 add logo
  client/components/Goals/GoalsMenu.js
Labels: enhancement

#66 Fix the console.log error
  client/routes.js
  client/store/user.js
Labels: bug

#67 Remove navbar
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/BeforeLogin/DesktopContainer.js
  client/components/BeforeLoginPages/HomePage.js
  package-lock.json
  package.json
Labels: enhancement

#68 update the user home page
  client/components/UserHomeCalender.js
  client/components/user-home.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
Labels: enhancement

#70 Update the css
  client/components/AccountTable.js
  client/components/AfterLogin/AfterLoginDesktopContainer.js
  client/components/AfterLogin/AfterLoginMobileContainer.js
  client/components/BillForm.js
  client/components/Words.js
  client/components/user-home.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
  public/words.css
Labels: enhancement

#73 update houseForm
  client/components/Goals/House.js
  client/store/houseForm.js
Labels: enhancement

#75 Resolve various bugs on the site
  client/components/BillAlert.js
  client/components/Loading.js
  client/components/PhoneAlert.js
  client/components/user-home.js
  client/store/emergencyGoal.js
  package-lock.json
  public/loading.css
  public/pictures/Philip.png
Labels: bug

#77 fix heroku deploy error
  public/index.html
Labels: bug, enhancement

#78 changed readme content
  README.md
Labels: enhancement
